language: php

php:
  - 5.6
  - 7.0
#  - hhvm

before_install:
  - pip install --user codecov

before_script:
  - wget http://getcomposer.org/composer.phar 
  - php composer.phar self-update
  - php composer.phar install --dev

script: 
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
